// <auto-generated />
using ECommerce.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250717164056_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for Product 1",
                            ImageUrl = "https://example.com/product1.jpg",
                            IsActive = false,
                            Name = "Product 1",
                            Price = 10.99m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for Product 2",
                            ImageUrl = "https://example.com/product2.jpg",
                            IsActive = true,
                            Name = "Product 2",
                            Price = 20.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for Product 3",
                            ImageUrl = "https://example.com/product3.jpg",
                            IsActive = true,
                            Name = "Product 3",
                            Price = 30.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description for Product 4",
                            ImageUrl = "https://example.com/product4.jpg",
                            IsActive = true,
                            Name = "Product 4",
                            Price = 40.99m,
                            Stock = 400
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description for Product 5",
                            ImageUrl = "https://example.com/product5.jpg",
                            IsActive = true,
                            Name = "Product 5",
                            Price = 50.99m,
                            Stock = 800
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
